name: 21cm-sbi
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26.*
  - scipy
  - matplotlib
  - healpy
  - pymaster
  - pip
  - pip:
      - torch
      - sbi==0.25.0
      - tqdm
